### ISSUE TITLE
请教一下，一直报错！

### ISSUE THREAD

**Issue by openai1998** [bingsanyu/feishu_minutes#8]
运行一直报错
```
python feishu_downloader.py
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\configparser.py", line 805, in get
    value = d[option]
            ~^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\collections\__init__.py", line 1006, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\collections\__init__.py", line 998, in __missing__
    raise KeyError(key)
KeyError: '妙记额度删除阈值（gb，填写了manager_cookie才有效）'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\GIthub\feishu_minutes\feishu_downloader.py", line 22, in <module>
    usage_threshold = float(config.get('下载设置', '妙记额度删除阈值（GB，填写了manager_cookie才有效）'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option '妙记额度删除阈值（gb，填写了manager_cookie才有效）' in section: '下载设置
```
![Snipaste_2024-08-24_17-50-17](https://github.com/user-attachments/assets/4afae2fb-18d3-4e2a-9aab-88666f0587dd)
![11](https://github.com/user-attachments/assets/fb255ab0-bc44-4394-b3ed-25a712b40e6b)

**Comment by bingsanyu** [comment]
抱歉，写错了，已修复。
